### PR TITLE
fix un-initialized value

### LINKED ISSUE #88: Coverity - Event member_not_init_in_gen_ctor
Event member_not_init_in_gen_ctor: The compiler-generated constructor for this class does not initialize "is_bond_enabled_".
https://github.com/ros/nodelet_core/blob/c833c6e64f7f228de2c2bd56a7c60d279b6910f4/nodelet/src/nodelet.cpp#L89

### PR DESCRIPTION
**Pull request by artivis**
Fix #88

### CODE REVIEW

**Comment by artivis** [comment]
CI's failing, likely related to https://github.com/ros/nodelet_core/issues/86.

File: nodelet/src/nodelet.cpp [hunk 1]
```diff
@@ -89,7 +89,7 @@ class NodeletArgumentParsing
     bool is_bond_enabled_;
 
   public:
-    //NodeletArgumentParsing() { };
+    NodeletArgumentParsing() : is_bond_enabled_(true) { };
```
Comment (flixr) [inline nodelet/src/nodelet.cpp:92]: Seems like you can also remove the `is_bond_enabled_ = true;` at the beginning of `parseArgs`.
Otherwise it looks good to me.

**Review by flixr — CHANGES_REQUESTED** [review]

File: nodelet/src/nodelet.cpp (hunk 1 above)
Comment (artivis) [reply nodelet/src/nodelet.cpp:92]: Thanks for the suggestion, I removed it :+1:.

**Comment by kyrofa** [comment]
Gentle ping on this fix.

**Review by sloretz — APPROVED** [review]
Thank you for the PR!
